config/routes.rb
Template::Application.routes.draw do
  resources :slides
  get "mailings/index"
  get "mailings/new"
  post "mailings/create"
  resources :notices
  resources :informations
  resources :years
  get "static_pages/index"
  get "static_pages/recognition"
  root "static_pages#cyvsa_home"
  resources :homes
  resources :users
  
  resources :services do 
    resources :slides
  end
  resources :sessions, only: [:new, :create, :destroy]
  get "project/index"
  get "portfolio/index"
  match '/signup',    to:     'users#new',                  via: 'get'
  match '/admin',     to:     'sessions#new',               via: 'get'
  match '/signout',   to:     'sessions#destroy',           via: 'delete'
  match '/dashboard', to:  'homes#dashboard',            via: 'get'
  

  

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many  :slides
	validates :icon , presence: true
	validates :content , presence: true
	validates :title, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :signed_in_user
  def index
    @services = Service.all

  end

  def show
    @service = Service.find(params[:id])
    @slides = @service.slides


  end

  def new
    @service = Service.new

  end

  def create
    @service = Service.new(service_params)
    if @service.save
      flash[:success] = "Creado exitosamente."
      redirect_to services_url
    else
      render 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])

  end

  def update

    @service = Service.find(params[:id])
    if @service.update_attributes(service_params)
      flash[:success]= "Actualización exitosa"
      redirect_to services_url

    else
      render 'edit'
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    flash[:success] = "Borrado exitosamente."
    redirect_to services_url

  end

  private
  def service_params
    params.require(:service).permit(:icon, :title, :content, :image_slide, :title_slide, :text_slide)

  end


end

app/helpers/services_helper.rb
module ServicesHelper

	def service(texto_default, titulo)
    text = texto_default

    if Service.first

      case titulo

      when "titulo"
        text = Service.first.title if !Service.first.title.blank?

      when "descripcion"
        text = Service.first.content if !Service.first.content.blank?

      end
    end
    text.to_s.html_safe
  end
  
	
end

app/views/services/edit.html.erb
<%= render 'services/form' %>

app/views/services/index.html.erb
#encoding: utf-8
<%- model_class = Service -%>
<div class="container content">
    <div class="panel panel-grey margin-bottom-40">
        <div class="panel-heading">
            <div class="pull-right">
              
            <%= link_to "Nuevo Servicio", new_service_path, :class => 'btn btn-success btn-xs' %>
             
            </div>
            <h3 class="panel-title"><i class="fa fa-globe"></i> Servicios</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        
                        <th><%= model_class.human_attribute_name(:Icono) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Titulo) %></th>
                        <th><%= model_class.human_attribute_name(:Comentario) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Acciones) %></th>
                    </tr>
                </thead>
                <tbody>
                    
                    <% @services.each do |service| %>
                    <tr>
                        
                        <td><i class="fa <%= "#{service.icon}"%> service-icon color-blue"></i></td>
                        <td><%= link_to service.title, service_path(service), class: "no-color nounderline " %></td>
                        <td ><%= service.content.to_s.html_safe %></td>
                        
                        <td>
                            
                            
                            <%= link_to "Editar", edit_service_path(service), :class => 'btn btn-warning btn-xs' %>
                            

                            <%= link_to "Borrar", service_path(service),:class => 'btn btn-danger btn-xs', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                            
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                
            </table>
        </div>
    </div>
</div>

app/views/services/new.html.erb
<%= render 'services/form' %>

app/views/services/show.html.erb
#encoding: utf-8
<%- model_class = Slide -%>
<div class="container content">
    <div class="panel panel-grey margin-bottom-40">
        <div class="panel-heading">
            <div class="pull-right">
              
           
             <%= link_to "Crear slide", new_service_slide_path(@service), :class => 'btn btn-success btn-xs' %>
            </div>
            <h3 class="panel-title"><i class="fa fa-globe"></i> Slide</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        
                        <th><%= model_class.human_attribute_name(:Imagen) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Titulo) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Comentario) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Acciones) %></th>
                    </tr>
                </thead>
                <tbody>
                    
                    <% @slides.each do |slide| %>
                    <tr>
                       
                        <td> <%=  image_tag slide.image_url(:thumb).to_s%></td>
                        <td><%= slide.title %></td>
                        <td class="col-sm-7"><%= slide.text.to_s.html_safe %></td>
                        
                        <td>
                            
                            
                            <%= link_to "Editar", edit_slide_path(slide), :class => 'btn btn-warning btn-xs' %>
                            

                            <%= link_to "Borrar", slide_path(slide),:class => 'btn btn-danger btn-xs', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                            
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                
            </table>
        </div>
    </div>
</div>