config/routes.rb
Template::Application.routes.draw do
  resources :slides
  get "mailings/index"
  get "mailings/new"
  post "mailings/create"
  resources :notices
  resources :informations
  resources :years
  get "static_pages/index"
  get "static_pages/recognition"
  root "static_pages#cyvsa_home"
  resources :homes
  resources :users
  
  resources :services do 
    resources :slides
  end
  resources :sessions, only: [:new, :create, :destroy]
  get "project/index"
  get "portfolio/index"
  match '/signup',    to:     'users#new',                  via: 'get'
  match '/admin',     to:     'sessions#new',               via: 'get'
  match '/signout',   to:     'sessions#destroy',           via: 'delete'
  match '/dashboard', to:  'homes#dashboard',            via: 'get'
  

  

end

app/models/notice.rb
class Notice < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :title , presence: true
	 validates :text , presence: true
	 validates :image , presence: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
	before_action :signed_in_user
	def index
		@notices = Notice.all
	end
	def new
		@notice = Notice.new
	end
	def create
		@notice = Notice.new(notice_params)
		if @notice.save
			flash[:success]= "cargada exitosamente."
			redirect_to notices_path

		else
			render 'new'
		end
	end

	def edit
		@notice = Notice.find(params[:id])
	end
	def update
		@notice = Notice.find(params[:id])
		if @notice.update_attributes(notice_params)
			flash[:success] = "Creado exitosamente."
			redirect_to notices_url

		else
			render 'edit'
		end
	end
	def destroy
		@notice = Notice.find(params[:id])
		@notice.destroy
		flash[:success] = "Borrado exitosamente."
		redirect_to @notice
	end
	private
	def notice_params
		params.require(:notice).permit([:title,:text,:image])
	end

end

app/helpers/notices_helper.rb
module NoticesHelper

	 # def img
  #   imagen_path = "/assets/info.jpeg"
  #   if Notice.first
  #      if !Notice.first.image.blank? 
  #       imagen_path = Notice.first.image
  #     end
  #   end
  #   imagen_path
  # end
end

   

app/views/notices/_form.html.erb
<%- model_class = Notice -%>
<div class="container content">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 reg-page">
			<dl class="dl-horizontal">
					
				<%= form_for @notice, :html => {:multipart => true, :class => 'form-horizontal'} do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<dl class="dl-horizontal">
				<dt><strong><%= model_class.human_attribute_name(:Imagen) %>:</strong></dt>
				<dd><%= image_tag @notice.image_url(:thumb).to_s, id: "image_url" %></dd></br>
				
				<div class="button">
					<div class="text">
						Selecciona una imagen
					</div>
					<%= f.file_field :image, data: {image: "image_url"}, class: "input_pluguin"  %>
				</div>
			</dl></dd></br>
			<div class="reg-header">
			</div>
			
	 <h2> Informativo</h2>
			
			<div class="control-group">
				<%= f.label :Titlulo, :class => 'control-label' %>
				<div class="controls">
					<%= f.text_field :title, :class => 'text_field', placeholder: 'Escribe un título  '%>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Descripcion, :class => 'control-label' %>
				<div class="controls">
					<%= f.text_area :text, :class => 'wysihtml5', placeholder: 'Escribe una Descripción ' %>
				</div>
			</div>
			</br></br>
			
			<% if params[:action] == "new" %>
			<div class="col-lg-3 text-right">
				<%= f.submit "Crear", class: "btn btn-primary" %>
			</div>
			<% else %>
			<div class="col-lg-3 text-right">
				<%= f.submit "Guardar", class: "btn btn-primary" %>
			</div>
			<% end %>
			<%= link_to "Cancelar", dashboard_path, class: 'btn btn-danger'%>
			<% end %>
		</div>
	</div>
</div>

app/views/notices/edit.html.erb
<%= render 'notices/form' %>

app/views/notices/index.html.erb
<%- model_class = Notice-%>
<div class="container content">
    <div class="panel panel-grey margin-bottom-40">
        <div class="panel-heading">
            <div class="pull-right">
              
            <%= link_to "Nuevo", new_notice_path, :class => 'btn btn-success btn-xs' %>
            </div>
            <h3 class="panel-title"><i class="fa fa-globe"></i> Informativo</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th><%= model_class.human_attribute_name(:Imagen) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Titulo) %></th>
                        <th><%= model_class.human_attribute_name(:Comentario) %></th>
                        <th class="col-sm-2"><%= model_class.human_attribute_name(:Acciones) %></th>
                    </tr>
                </thead>
                <tbody>
                    
                    <% @notices.each do |notice| %>
                    <tr>
                       
                        <td><%=  image_tag notice.image_url(:thumb).to_s%></td>
                        <td><%= notice.title %></td>
                        <td><%= notice.text.to_s.html_safe %></td>
                        
                        
                        <td>
                            
                            
                            <%= link_to "Editar", edit_notice_path(notice), :class => 'btn btn-warning btn-xs' %>

                            <%= link_to "borrar", notice_path(notice),:class => 'btn btn-danger btn-xs', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                             
                            
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                
            </table>
        </div>
    </div>
</div>

app/views/notices/new.html.erb
<%= render 'notices/form' %>