config/routes.rb
Template::Application.routes.draw do
  resources :slides
  get "mailings/index"
  get "mailings/new"
  post "mailings/create"
  resources :notices
  resources :informations
  resources :years
  get "static_pages/index"
  get "static_pages/recognition"
  root "static_pages#cyvsa_home"
  resources :homes
  resources :users
  
  resources :services do 
    resources :slides
  end
  resources :sessions, only: [:new, :create, :destroy]
  get "project/index"
  get "portfolio/index"
  match '/signup',    to:     'users#new',                  via: 'get'
  match '/admin',     to:     'sessions#new',               via: 'get'
  match '/signout',   to:     'sessions#destroy',           via: 'delete'
  match '/dashboard', to:  'homes#dashboard',            via: 'get'
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 8}

  def User.new_remember_token
    SecureRandom.urlsafe_base64

  end



  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :signed_in_user
  before_action :correct_user,   only: [:edit, :update, :destroy]
  #before_action :admin_user,     only: [:edit, :update, :create, :destroy]

  def index
    @users = User.all
    
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Registro actualizado"
      redirect_to users_path

    else
      render 'edit'
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
      
      flash[:success] = "Welcome !"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Borrado exitosamente."
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end

  # def signed_in_user
  #     unless signed_in?
  #       store_location
  #       redirect_to admin_url, notice: "Please sign in."
  #     end
   # end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(users_url) unless current_user?(@user) || current_user.admin?
  end

  # def admin_user
  #   @user = User.find(params[:id])
  #   redirect_to(users_url) unless current_user.admin?
  # end
end

app/helpers/users_helper.rb
#encoding: UTF-8
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container content">
  <div class="row">
    
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 reg-page">
      <div class="reg-header">
        <% if params[:action] == "new"  %>
            <h2>Registra una cuenta nueva. </h2>
        <% else %>
            <h2>Editar cuenta. </h2>
        <% end %>
        <!-- <p>Already Signed Up? Click <%= link_to "Sign in", admin_path %>  to login your account.</p -->
      </div>
      <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
              <%= f.label :name, "Nombre" %>
              <%= f.text_field :name, class: 'form-control margin-bottom-20', placeholder:"Nombre" %>
              <%= f.label :email %>
              <%= f.text_field :email, :autofocus => false, class: 'form-control margin-bottom-20', placeholder:"Email" %>
              <%= f.label :password, " Contraseña" %>
              <%= f.password_field :password, autocomplete: "off", :class => "form-control margin-bottom-20", placeholder:"Contraseña" %>
              <%= f.label :password_confirmation, "Confirmar contraseña" %>
              <%= f.password_field :password_confirmation, :class => "form-control margin-bottom-20",placeholder:"Confirma contraseña"%>
              <%= f.label :Administrador %>
              <%= f.check_box :admin %> 
              </br></br>
        <div class="col-lg-5 text-right">
        
        <% if params[:action] ==  "new" || params[:action] == "create"%>
          <%= f.submit "Crear cuenta", class: "btn btn-primary" %>
        
        <%else%>
          <%= f.submit "Guardar cambios",  class: "btn btn-primary" %> 
        <%end%>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%= render 'users/form' %>

app/views/users/index.html.erb
<div class="profile container content">
    <div class="row">
        <!--Left Sidebar-->
        <div class="col-md-3 md-margin-bottom-40">
            
            <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                <li class="list-group-item active">
                    <a href="/dashboard"><i class="fa fa-bar-chart-o"></i>CYVSA </a>
                    
                </li>
                <li class="list-group-item" >
                <%= link_to  dashboard_path, class: 'nounderline' do %>
                        <i class="fa fa-user"></i>Hola: <%= current_user.name%>
                        <% end %>
                    </li>


                <% if current_user.admin? %>
                <li class="list-group-item ">
                    <%= link_to  signup_path(@user), class: ' disabled'  do%>
                    <i class="fa fa-group"></i> Agregar nuevo usuario
                    <%end%>
                    
                </li>
                <%end %>
                
                <li class="list-group-item list-toggle">
                    <a class="accordion-toggle collapsed" href="#collapse-timeline" data-toggle="collapse"><i class="fa fa-cog"></i> Menu</a>
                    <ul id="collapse-timeline" class="collapse" style="height: 0px;">
                        <li class="list-group-item ">
                            <%= link_to  dashboard_path, class: 'nounderline' do %>
                            <i class="fa fa-cubes"></i> Dashboard
                            <% end %>
                        </li>
                        <li class="list-group-item">
                            <%= link_to signout_path, method: "delete", class: 'nounderline'  do%>  <i class="fa fa-sign-out fa-fw"></i> Salir
                            <%end%>
                        </li>
                        
                    </ul>
                </li>
                
                
                
            </ul>
            
            
        </div>
        <!--End Left Sidebar-->
        
        <div class="col-md-9">
            <!--Profile Body-->
            <div class="profile-body">
                
                <!--Table Search v1-->
                <div class="table-search-v1 margin-bottom-20">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th class="hidden-sm">Email</th>
                                    <th> Rol </th>
                                    <th width="300">Botones</th>
                                    
                                    
                                </tr>
                            </thead>
                            <tbody>
                                <% @users.all.each do |user| %>
                                <tr>
                                    <td>
                                        <%= user.name %>
                                    </td>
                                    <td class="td-width"> <%= user.email%> </td>
                                    <td>
                                        <% if user.admin?  %>
                                        Administrador
                                        <% else %>
                                        Usuario
                                        <% end %>
                                    </td>
                                    
                                    <td> <% if current_user?(user) || current_user.admin? %>
                                        <%= link_to "Editar", edit_user_path(user), :class => 'btn btn-warning btn-xs' %>
                                        
                                        <%= link_to "borrar", user_path(user),:class => 'btn btn-danger btn-xs', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                                        <% else %>
                                        
                                        <%= link_to "Editar", edit_user_path(user), :class => 'btn btn-warning btn-xs disabled' %>
                                        
                                        <%= link_to "borrar", user_path(user),:class => 'btn btn-danger btn-xs disabled', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
                
                
                
                
                
                
                
            </div>
            <!--End Profile Body-->
        </div>
        </div><!--/end row-->
    </div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
 <%= render 'users/form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>