config/routes.rb
Template::Application.routes.draw do
  resources :slides
  get "mailings/index"
  get "mailings/new"
  post "mailings/create"
  resources :notices
  resources :informations
  resources :years
  get "static_pages/index"
  get "static_pages/recognition"
  root "static_pages#cyvsa_home"
  resources :homes
  resources :users
  
  resources :services do 
    resources :slides
  end
  resources :sessions, only: [:new, :create, :destroy]
  get "project/index"
  get "portfolio/index"
  match '/signup',    to:     'users#new',                  via: 'get'
  match '/admin',     to:     'sessions#new',               via: 'get'
  match '/signout',   to:     'sessions#destroy',           via: 'delete'
  match '/dashboard', to:  'homes#dashboard',            via: 'get'
  

  

end

app/models/year.rb
class Year < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :title , presence: true
	#validates :text , presence: true
	#validates :image , presence: true
	validates :date, presence: true
	validates :date, length: { is: 4 }
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
	skip_before_action :require_login, only: [:index, :show]
	def index
		if params[:tipo]
			@years = Year.order(:date).where(:tipo => 'Reconocimiento')

		else

			@years = Year.order(:date).where(:tipo => 'Historia')
		end
	end


	def index_admin

	end

	def show
		@year = Year.find(params[:id])

	end

	def new
		@year = Year.new
	end

	def create
		@year = Year.new(year_params)
		if @year.save
			flash[:success] = "cargado exitosamente."

				if @year.tipo == 'Reconocimiento'
					redirect_to years_path(tipo: 'Reconocimiento')
					
				else
				redirect_to years_path
				end

		else
			render :action => 'new'
		end
	end

	def edit
		@year = Year.find(params[:id])

	end

	def update

		@year = Year.find(params[:id])
		if @year.update_attributes(year_params)
			flash[:success]= "creada exitosamente"
			if @year.tipo == 'Historia'
				redirect_to years_url
			else
				redirect_to years_url(tipo: 'Reconocimiento')
			end

		else
			render 'edit'
		end
	end

	def destroy
		@year = Year.find(params[:id])
		@year.destroy
		flash[:success] = "Borrado exitosamente."

				if @year.tipo == 'Reconocimiento'
					redirect_to years_path(tipo: 'Reconocimiento')
					
				else
				redirect_to years_path
				end
	end

	private
	def year_params
		params.require(:year).permit(:title, :text, :image, :date, :tipo)


	end

end

app/helpers/years_helper.rb
module YearsHelper

	def year (texto_default, titulo)
    text = texto_default

    if Year.all

      case titulo

      when "titulo"
        text = Year.first.title if !Year.first.title.blank?

      when "descripcion"
        text = Year.first.text if !Year.first.text.blank?
      
    	when "fecha"
        text = Year.first.date if !Year.first.date.blank?
      end
    end
    text.to_s.html_safe
  end

  


  

 def imagen
    imagen_path = "/assets/h.jpg"
    if Year.first
       if !Year.first.image 
        imagen_path = Year.first.image.blank?
      end
    end
    imagen_path
  end
end

app/views/years/_form.html.erb
<%- model_class = Year -%>
<div class="container content">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 reg-page">
			
			
			<%= form_for @year, :html => {:multipart => true, :class => 'form-horizontal'} do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<dl class="dl-horizontal">
				<dt><strong><%= model_class.human_attribute_name(:Imagen) %>:</strong></dt>
				<dd><%= image_tag @year.image_url(:thumb).to_s, id: "image_url" %></dd></br>
				
				<div class="button">
					<div class="text">
						Selecciona una imagen
					</div>
					<%= f.file_field :image, data: {image: "image_url"}, class: "input_pluguin"  %>
				</div>
			</dl></dd></br>
			<div class="reg-header">
			</div>
			<div class="control-group">
				<%= f.label :Titlulo, :class => 'control-label' %>
				<div class="controls">
					<%= f.text_field :title, :class => 'text_field', placeholder: 'Escribe un título' %>
				</div>
			</div>
			<% if params[:tipo] || @year.tipo == "Historia" %>
			<div class="control-group">
				<%= f.label :Descripcion, :class => 'control-label' %>
				<div class="controls">
					<%= f.text_area :text, :class => 'wysihtml5', placeholder: 'Escribe una Descripción' %>
				</div>
			</div>
			
			<% end %>
			<div class="control-group">
				<%= f.label :Fecha, :class => 'control-label' %>
				<div class="controls">
					<%= f.text_field :date, :class => 'text_field', placeholder: 'Escribe una fecha' %>
				</div>
				<div class="control-group">
					
					<div class="controls">
						<% if params[:action] != "edit"  %>
						
							<% if params[:tipo] || @year.tipo == "Historia"  %>
									<%= f.text_field :tipo, value: 'Historia', hidden: true%>
							<% else %>
									<%= f.text_field :tipo, value: 'Reconocimiento', hidden: true %>
							<% end %>
						<% end %>
					</div></br></br>
					
					<% if params[:action] == "new" %>
					<div class="col-lg-3 text-right">
						<%= f.submit "Crear", class: "btn btn-primary" %>
					</div>
					<% else %>
					<div class="col-lg-3 text-right">
						<%= f.submit "Guardar", class: "btn btn-primary" %>
					</div>
					<% end %>
					<%= link_to "Cancelar", dashboard_path, class: 'btn btn-danger'%>
					
					<% end %>
				</div>
			</div>
		</div>

app/views/years/_index_admin.html.erb
<%- model_class = Year -%>
<div class="container content">
    <div class="panel panel-grey margin-bottom-40">
        <div class="panel-heading">
            <div class="pull-right " >
                <% if params[:tipo] == 'Reconocimiento' %>
                <%= link_to 'Neuvo Reconocimiento', new_year_path,  tipo: "Reconocimiento", class: "btn btn-success btn-xs" %>
                
                <% else %>
                <%= link_to ' Nueva Historia', new_year_path(tipo: "Historia") , class: "btn btn-success btn-xs" %>
                <% end %>
                
            </div>
            <% if params[:tipo] == 'Reconocimiento' %>
            <h3 class="panel-title"><i class="fa fa-globe"></i> Reconocimientos</h3>
            
            <% else %>
            <h3 class="panel-title"><i class="fa fa-globe"></i> Historia</h3>
            <% end %>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        
                        <th><%= model_class.human_attribute_name(:Imagen) %></th>
                        
                        <th><%= model_class.human_attribute_name(:Titulo) %></th>
                        
                        <% if params[:tipo] == 'Reconocimiento' %>
                        <% else %>
                        <th><%= model_class.human_attribute_name(:Comentario) %></th>
                        <% end %>
                        <th><%= model_class.human_attribute_name(:Año) %></th>
                        <th><%= model_class.human_attribute_name(:Acciones) %></th>
                    </tr>
                </thead>
                <tbody>
                    
                    <% @years.each do |year| %>
                    <tr>
                        
                        <td><%=  image_tag year.image_url(:thumb).to_s%></td>
                        <td><%= year.title %></td>
                        
                        <% if params[:tipo] == 'Reconocimiento' %>
                        <% else %>
                        <td class="col-sm-6"><%= year.text.to_s.html_safe %></td>
                        <% end %>
                        <td><%= year.date %></td>
                        
                        <td>
                            <% if params[:tipo] %>
                            <%= link_to "Editar",  edit_year_path(year), :class => 'btn btn-warning btn-xs' %>
                            
                            <% else %>
                            <%= link_to "Editar",  edit_year_path(year,  tipo: "Historia"), class: 'btn btn-warning btn-xs' %>
                            <% end %>
                            
                            
                            
                            <%= link_to "borrar", year_path(year),:class => 'btn btn-danger btn-xs', method: :delete, data: {confirm: "¿Está usted seguro que quiere borrar este servicio?"}%>
                            
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                
            </table>
        </div>
    </div>
</div>

app/views/years/_index_users.html.erb
<!--=== Content Part ===-->
<div class="title-box">
    <div class="title-box-text">Nuestra<span class="color-green">Historia</span> </div>
    <p>Cumpliendo con la VISIÓN de crecer y servir, CYVSA contruye día a día una trayectoria de exito junto con sus clientes.</p>
</div>
<div class="container content">
    <ul class="timeline-v1">

        <% @years.all.each_with_index do |t, index| %>
 
        <li <% if (index+1)%2 == 0 %>  class="timeline-inverted"
            class="timeline-inverted" <% end %>>
            <div class="timeline-badge primary"><i class="glyphicon glyphicon-record"></i></div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    <img class="img-responsive" src="<%= t.image %>" alt="">
                </div>
                <div class="timeline-body text-justify">
                    <ul class="list-unstyled list-inline blog-info">
                         <%= t.date %></li>
                    </ul>
                    <h2><%= t.title.to_s.html_safe  %></h2>
                    <p><%= t.text.to_s.html_safe %></p>
                    
                </div>
                
            </div>
        </li>
        <% end %>
        
        <li class="clearfix" style="float: none;"></li>
    </ul>
</div>

<!--/container-->
<!-- End Content Part -->

app/views/years/edit.html.erb
<%= render 'years/form' %>

app/views/years/index.html.erb
<% if current_user %>
    <% if current_user.admin %>
    <%= render "/years/index_admin" %>
    <%end %>
<% else %>
    <%= render "/years/index_users" %>
<% end %>

app/views/years/new.html.erb
<%= render 'years/form' %>